export const SET_LAST_OPEN = 'SET_LAST_OPEN';
export const SET_SUBMISSIONS = 'SET_SUBMISSIONS';
export const ADD_SUBMISSION = 'ADD_SUBMISSION';
export const SET_CURRENT_ROW = 'SET_CURRENT_ROW';
export const NEXT_SUBMISSION = 'NEXT_SUBMISSION';
export const PREV_SUBMISSION = 'PREV_SUBMISSION';
