export const SET_LAST_OPEN = 'SET_LAST_OPEN';
export const SET_SUBMISSIONS = 'SET_SUBMISSIONS';
export const ADD_SUBMISSION = 'ADD_SUBMISSION';
export const SET_CURRENT_ROW = 'SET_CURRENT_ROW';
export const NEXT_SUBMISSION = 'NEXT_SUBMISSION';
export const PREV_SUBMISSION = 'PREV_SUBMISSION';
export const OPEN_SUBMISSIONS = 'OPEN_SUBMISSIONS';
export const LOAD_SUBMISSIONS = 'LOAD_SUBMISSIONS';


export const CREATE_COMMENT = 'CREATE_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';

export const CREATE_CORRECTOR = 'CREATE_CORRECTOR';
export const UPDATE_CORRECTOR = 'UPDATE_CORRECTOR';
export const DELETE_CORRECTOR = 'DELETE_CORRECTOR';

export const CREATE_EXERCISE = 'CREATE_EXERCISE';
export const UPDATE_EXERCISE = 'UPDATE_EXERCISE';
export const DELETE_EXERCISE = 'DELETE_EXERCISE';

export const CREATE_LECTURE = 'CREATE_LECTURE';
export const UPDATE_LECTURE = 'UPDATE_LECTURE';
export const DELETE_LECTURE = 'DELETE_LECTURE';

export const CREATE_RATING = 'CREATE_RATING';
export const UPDATE_RATING = 'UPDATE_RATING';
export const DELETE_RATING = 'DELETE_RATING';

export const CREATE_SUBMISSION = 'CREATE_SUBMISSION';
export const UPDATE_SUBMISSION = 'UPDATE_SUBMISSION';
export const DELETE_SUBMISSION = 'DELETE_SUBMISSION';

export const CREATE_SUBMISSION_CORRECTION = 'CREATE_SUBMISSION_CORRECTION';
export const UPDATE_SUBMISSION_CORRECTION = 'UPDATE_SUBMISSION_CORRECTION';
export const DELETE_SUBMISSION_CORRECTION = 'DELETE_SUBMISSION_CORRECTION';

export const CREATE_TASK = 'CREATE_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const DELETE_TASK = 'DELETE_TASK';


