export const AUTOCORRECTION_START = 'AUTOCORRECTION_START';
export const AUTOCORRECTION_STOP = 'AUTOCORRECTION_STOP';
export const AUTOCORRECTION_PROGRESS = 'AUTOCORRECTION_PROGRESS';
export const AUTOCORRECTION_SUCCESSFUL = 'AUTOCORRECTION_SUCCESSFUL';
export const AUTOCORRECTION_FAILED = 'AUTOCORRECTION_FAILED';
export const AUTOCORRECTION_CANCEL = 'AUTOCORRECTION_CANCEL';
export const AUTOCORRECTION_CANCEL_PENDING = 'AUTOCORRECTION_CANCEL_PENDING';
export const AUTOCORRECTION_CANCELED = 'AUTOCORRECTION_CANCELED';
