export const BACKUP_START = 'BACKUP_START';
export const BACKUP_STOP = 'BACKUP_STOP';
export const BACKUP_ONCE = 'BACKUP_ONCE';
export const BACKUP_SUCCESSFUL = 'BACKUP_SUCCESSFUL';
export const BACKUP_FAILED = 'BACKUP_FAILED';
