export const IMPORT_START = 'IMPORT_START';
export const IMPORT_STOP = 'IMPORT_STOP';
export const IMPORT_PROGRESS = 'IMPORT_PROGRESS';
export const IMPORT_SUCCESSFUL = 'IMPORT_SUCCESSFUL';
export const IMPORT_FAILED = 'IMPORT_FAILED';
export const IMPORT_CONFLICTS = 'IMPORT_CONFLICTS';
