export const CHECK_FOR_UPDATE_PENDING = 'CHECK_FOR_UPDATE_PENDING';
export const CHECK_FOR_UPDATE_SUCCESS = 'CHECK_FOR_UPDATE_SUCCESS';
export const CHECK_FOR_UPDATE_FAILURE = 'CHECK_FOR_UPDATE_FAILURE';
export const DOWNLOAD_UPDATE_PENDING = 'DOWNLOAD_UPDATE_PENDING';
export const DOWNLOAD_UPDATE_SUCCESS = 'DOWNLOAD_UPDATE_SUCCESS';
export const DOWNLOAD_UPDATE_FAILURE = 'DOWNLOAD_UPDATE_FAILURE';
export const QUIT_AND_INSTALL_UPDATE = 'QUIT_AND_INSTALL_UPDATE';
